# Generated by Django 4.1.4 on 2023-03-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_patient_payment_advance_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('service_name', models.CharField(max_length=100)),
                ('cost_of_treatment', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_payment',
            name='cost_of_treatment',
        ),
        migrations.RemoveField(
            model_name='patient_payment',
            name='service_name',
        ),
    ]
