# Generated by Django 4.1.4 on 2023-04-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_delete_services_patient_payment_cost_of_treatment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('room_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Room_A',
        ),
    ]
