# Generated by Django 4.1.4 on 2023-04-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rooms_rename_room_room_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_data',
            field=models.DateField(),
        ),
    ]
