# Generated by Django 4.1.4 on 2023-04-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_rooms_current_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='is_allocated',
        ),
    ]
