# Generated by Django 4.1.4 on 2023-04-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_rooms_is_allocated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='current_booking',
        ),
        migrations.AddField(
            model_name='rooms',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
    ]
