# Generated by Django 4.1.4 on 2023-04-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_allotment_delete_room_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='is_allocated',
            new_name='available',
        ),
    ]
