# Generated by Django 4.1.4 on 2023-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_rename_is_allocated_rooms_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
