# Generated by Django 4.1.4 on 2023-04-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_booking_rename_room_no_rooms_roomnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('cost_of_treatment', models.IntegerField()),
                ('patient_id', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient_payment',
            name='cost_of_treatment',
        ),
        migrations.RemoveField(
            model_name='patient_payment',
            name='service_name',
        ),
    ]
