# Generated by Django 4.1.4 on 2023-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_service_payment_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service_payment',
        ),
        migrations.AddField(
            model_name='patient_payment',
            name='cost_of_treatment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient_payment',
            name='service_name',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
