# Generated by Django 4.1.4 on 2023-04-10 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_delete_service_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_payment',
            name='cost_of_treatment',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient_payment',
            name='service_name',
            field=models.CharField(max_length=100),
        ),
    ]
