# Generated by Django 4.1.4 on 2023-04-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_userpreferences_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='preferences',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserPreferences',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
